import React from 'react';
import ReactDOM from 'react-dom/client';
import * as Sentry from '@sentry/react';
import { registerSW } from 'virtual:pwa-register';
import App from './App';
import { ErrorView } from './components/ErrorView';
import { initThemeOnce } from './hooks/useTheme';

// Apply the saved theme before React paints, so there's no light flash.
initThemeOnce();

const dsn = import.meta.env.VITE_SENTRY_DSN_CLIENT;

Sentry.init({
  dsn,
  enabled: !!dsn,
  environment: import.meta.env.MODE,
  tracesSampleRate: 0.1,
  integrations: [Sentry.browserTracingIntegration()],
});

// Register the Workbox service worker generated by vite-plugin-pwa (see
// vite.config.ts). It runs NetworkOnly for /api/, falls back to index.html for
// navigations, and auto-updates (registerType: 'autoUpdate'). The old
// hand-written public/sw.js was removed — it cache-first'd everything and
// shadowed this one.
registerSW({
  immediate: true,
  onRegisterError(error) {
    Sentry.captureException(error);
  },
});

ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <Sentry.ErrorBoundary
      fallback={({ resetError }) => (
        <ErrorView message="Algo salió mal. Intenta de nuevo." onRetry={resetError} />
      )}
    >
      <App />
    </Sentry.ErrorBoundary>
  </React.StrictMode>
);
